---
- name: Create local directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
  become: no
  delegate_to: localhost
  run_once: yes
  with_items:
   - '{{ inventory_dir }}/dynamic_vars'
   - '{{ inventory_dir }}/dynamic_vars/group'
   - '{{ inventory_dir }}/dynamic_vars/host'
   - '{{ inventory_dir }}/dynamic_vars/files'
   - '{{ inventory_dir }}/dynamic_vars/files/config'
   - '{{ inventory_dir }}/dynamic_vars/files/config/dns'
   - '{{ inventory_dir }}/dynamic_vars/files/config/dns/zone-file'
   - '{{ inventory_dir }}/dynamic_vars/files/config/dhcp'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ldap'
   - '{{ inventory_dir }}/dynamic_vars/files/config/kubernetes'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/root-cert'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/root-cert/public'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/intermediate-cert'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/intermediate-cert/public'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/server-cert'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/server-cert/private'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/server-cert/csr'
   - '{{ inventory_dir }}/dynamic_vars/files/config/ssl/server-cert/public'
   - '{{ label_directory }}'

- name: Create local files
  file:
    path: "{{ item }}"
    state: touch
    mode: '0664'
  become: no
  delegate_to: localhost
  run_once: yes
  changed_when: False
  with_items:
   - '{{ inventory_dir }}/dynamic_vars/group/kubernetes.yml'
   - '{{ inventory_dir }}/dynamic_vars/group/initial.yml'